version: "3"

services:
  api:
    env_file:
      - ./server/.env.production
    image: $AWS_API_IMAGE
    ports:
      - "5001:5001"
    logging:
      driver: awslogs
      options:
        awslogs-group: zigoom-group
        awslogs-region: $AWS_REGION
        awslogs-stream-prefix: api
