name: "CI/CD for Client"

on:
  push:
    branches:
      - "main"
    paths:
      - "client/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Trigger client deployment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: aws lambda invoke --function-name ${{ secrets.AWS_LAMBDA_CLIENT }} ./out.json
